**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [3]:
x = np.array([0,0,0])
x

array([0, 0, 0])

**TASK:** define (2 x 2) matrix 'A' 


In [6]:
A = np.array([[0,0],[0,0]])
A

array([[0, 0],
       [0, 0]])

**TASK:** define (2 x 2) matrix 'B'

In [88]:
B = np.array([[1,1],[1,1]])
B

array([[1, 1],
       [1, 1]])

**TASK:** check the type of 'x'

In [8]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [9]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [10]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [61]:
A.shape

(2, 2)

**TASK:** 

In [ ]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [18]:
def have_same_shape(array_1, array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        print('Arrays must have same shape!')
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [19]:
have_same_shape(A,x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [20]:
have_same_shape(A,B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [84]:
def matrix_addition(A, B):
    C == np.add(A, B)
    return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [89]:
matrix_addition(A, B)
print(C)
have_same_shape(A, B)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


C:\Users\rwadi\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


True

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [58]:
def multiple_matrix_addition(list):
    return np.add(matrix_addition(list[0], list[1]), matrix_addition(list[2], list[3]))

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [59]:
multiple_matrix_addition(list = [A,A,B,B])

array([[2, 2],
       [2, 2]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [70]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        print(f'Resulting shape is {array_a.shape[0]}, {array_b.shape[1]}')
        return True
    else:
        print('Matrices can not be multiplied')

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [71]:
can_multiply(A, B)

Resulting shape is 2, 2


True

**TASK:**  define matrix (3 x 2) matrix C

In [72]:
C = np.zeros((3,2))

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [73]:
can_multiply(A, C)

Matrices can not be multiplied


**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [74]:
can_multiply(C, A)

Resulting shape is 3, 2


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [76]:
def matrix_multiplication(array_a, array_b):
    can_multiply(array_a, array_b)
    return np.dot(array_a, array_b)

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [77]:
matrix_multiplication(C, B)

Resulting shape is 3, 2


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [78]:
matrix_multiplication(A, C)

Matrices can not be multiplied


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)