Kata 1

In [102]:
input_str = input("Enter a list elements separated by space ")
input_list = input_str.split()
input_list.sort()
print(input_list)
max1 = input_list[-1]
max2 = input_list[-2]
def sumLargestNumbers():
    return int(max1) + int(max2)

print(sumLargestNumbers())

Enter a list elements separated by space  5 1 2 6 8 2


['1', '2', '2', '5', '6', '8']
14


Kata 2

In [105]:
def conditionalSum(values, condition):
    odd_values = []
    even_values = []
    for i in values:
        if condition == 'odd' and i%2 > 0:
            odd_values.append(i)
        elif condition == 'even' and i%2 == 0:
            even_values.append(i)
        else:
            pass
    if condition == 'odd':
        return sum(odd_values)
    else:
        return sum(even_values)
    
print(conditionalSum([1,2,3,4], 'even'))

6


Kata 3

In [7]:
def numberOfVowels(data):
    alphabet = list(data)
    vowel_list = []
    for k in alphabet:
        if k == 'a' or k == 'i' or k == 'u' or k == 'e' or k == 'o':
            vowel_list.append(k)
    return len(vowel_list)

print(numberOfVowels('apple'))

2


Kata 4

In [53]:
def instructorWithLongestName(instructors):
    sort1 = instructors.items()
    sort_by_longest_name = sorted(sort1)
    return sort_by_longest_name[0]

print(instructorWithLongestName([
  {name: "Samuel", course: "iOS"},
  {name: "Jeremiah", course: "Data"},
  {name: "Ophilia", course: "Web"},
  {name: "Donald", course: "Web"}
]))

NameError: name 'name' is not defined

Kata 5

In [52]:
def urlEncode(text):
    replacement = ''
    for i in range(len(text)):
        if(text[i] == ' '):
            replacement = replacement + '%20'
        else:
            replacement = replacement + text[i]
    return replacement
    
print(urlEncode('Lighthouse Labs'))

Lighthouse%20Labs


Kata 6

In [89]:
import numpy as np

def whereCanIPark(spots, vehicle):
    spots = np.empty([6,6], dtype = str)
    if vehicle == 'regular':
        parking_spot = np.where(spots == 'R')
        coordinate = list(zip(parking_spot[0], parking_spot[1]))
        for coord in coordinate:
            print(coord)
    elif vehicle == 'small':
        parking_spot1 = np.where(spots == 'R')
        coordinate1 = list(zip(parking_spot1[0], parking_spot1[1]))
        for coord in coordinate1:
            print(coord)
        parking_spot2 = np.where(spots == 'S')
        coordinate2 = list(zip(parking_spot2[0], parking_spot2[1]))
        for coord in coordinate2:
            print(coord)
    elif vehicle == 'motorcycle':
        parking_spot1 = np.where(spots == 'R')
        coordinate1 = list(zip(parking_spot1[0], parking_spot1[1]))
        for coord in coordinate1:
            print(coord)
        parking_spot2 = np.where(spots == 'S')
        coordinate2 = list(zip(parking_spot2[0], parking_spot2[1]))
        for coord in coordinate2:
            print(coord)
        parking_spot3 = np.where(spots == 'M')
        coordinate3 = list(zip(parking_spot3[0], parking_spot3[1]))
        for coord in coordinate3:
            print(coord)
    else:
        print('None')
        
print(whereCanIPark(
  [['s', 's', 's', 'S', 'R', 'M'], 
    ['s', 'M', 's', 'S', 'r', 'M'], 
    ['s', 'M', 's', 'S', 'r', 'm'], 
    ['S', 'r', 's', 'm', 'r', 'M'], 
    ['S', 'r', 's', 'm', 'r', 'M'],
    ['S', 'r', 'S', 'M', 'M', 'S']], 'regular'))

None


Kata 7

In [79]:
def checkAir(samples, threshold):
    clean_air = []
    for s in samples:
        if s =='clean':
            clean_air.append(s)
        else:
            pass
    if len(clean_air) / len(samples) > threshold:
        print('Clean')
    else:
        print('Polluted')

print(checkAir(
  ['dirty', 'dirty', 'dirty', 'dirty', 'clean'],
  0.25
))

Polluted
None


Kata 6 Stretch

In [1]:
def repeatNumbers(data):
    n=[]
    for i in range(len(data)):
        n.append(str(data[i][0])*data[i][1])
    return n

print(repeatNumbers([[1, 10]]))
print(repeatNumbers([[1, 2], [2, 3]]))

['1111111111']
['11', '222']


Kata 7 Stretch 

In [3]:
def camelCase(input):
    to_convert=input.rsplit()
    new_to_convert=[]
    for i in range(len(to_convert)):
        if i != 0:
            new_to_convert+=to_convert[i].capitalize()
        else:
            new_to_convert+=to_convert[i].lower()
    return ''.join(new_to_convert)

print(camelCase("this is a string"))
print(camelCase("loopy lighthouse"))
print(camelCase("supercalifragalisticexpialidocious"))

thisIsAString
loopyLighthouse
supercalifragalisticexpialidocious


Kata 8 Stretch

In [11]:
import numpy as np
def multiplicationTable(value):
    x=np.array([range(1, value+2)])
    y=np.ones([value+1, value+1])
    y[0,:]=x
    y[:,0]=x
    for i in range(1, len(y)):
        for j in range(1, len(y)):
            y[i,j]=i*j
    z=np.delete(y, 0, 0)
    x=np.delete(z, 0, 1)
    return x.astype(int)

print(multiplicationTable(3))
print(multiplicationTable(5))
print(multiplicationTable(12))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
[[  1   2   3   4   5   6   7   8   9  10  11  12]
 [  2   4   6   8  10  12  14  16  18  20  22  24]
 [  3   6   9  12  15  18  21  24  27  30  33  36]
 [  4   8  12  16  20  24  28  32  36  40  44  48]
 [  5  10  15  20  25  30  35  40  45  50  55  60]
 [  6  12  18  24  30  36  42  48  54  60  66  72]
 [  7  14  21  28  35  42  49  56  63  70  77  84]
 [  8  16  24  32  40  48  56  64  72  80  88  96]
 [  9  18  27  36  45  54  63  72  81  90  99 108]
 [ 10  20  30  40  50  60  70  80  90 100 110 120]
 [ 11  22  33  44  55  66  77  88  99 110 121 132]
 [ 12  24  36  48  60  72  84  96 108 120 132 144]]
